/*
  # Complete SuperCoach AI Database Schema

  1. New Tables
    - `super_coaches` - AI coaches with personality types and course assignments
    - `courses` - Course content with versioning support and JSON modules
    - `students` - Student profiles with JSON enrollment and progress tracking
    - `conversations` - Chat history between students and coaches
    
  2. Security
    - Enable RLS on all tables
    - Add policies for authenticated users
    
  3. Sample Data
    - Comprehensive seed data matching the application structure
*/

-- Create custom types
CREATE TYPE task_status AS ENUM ('pending', 'completed');

-- Create super_coaches table (matches your app structure)
CREATE TABLE IF NOT EXISTS super_coaches (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL,
  personality_type text NOT NULL CHECK (personality_type IN ('friendly', 'professional', 'motivational', 'supportive', 'direct')),
  description text NOT NULL,
  avatar text DEFAULT '',
  courses_assigned jsonb DEFAULT '[]',
  created_at timestamptz DEFAULT now(),
  is_active boolean DEFAULT true
);

-- Create courses table (matches your app structure with JSON modules)
CREATE TABLE IF NOT EXISTS courses (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title text NOT NULL,
  description text NOT NULL,
  status text DEFAULT 'draft' CHECK (status IN ('draft', 'live', 'archived')),
  version integer DEFAULT 1,
  modules jsonb DEFAULT '[]',
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  enrolled_students integer DEFAULT 0,
  completion_rate integer DEFAULT 0,
  super_coach_id integer REFERENCES super_coaches(id),
  base_id integer,
  is_current_version boolean DEFAULT true
);

-- Create students table (matches your app structure with JSON fields)
CREATE TABLE IF NOT EXISTS students (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL,
  email text NOT NULL,
  avatar text,
  status text DEFAULT 'new' CHECK (status IN ('new', 'in-progress', 'stuck', 'completed')),
  enrolled_courses jsonb DEFAULT '[]',
  progress jsonb DEFAULT '[]',
  joined_at timestamptz DEFAULT now(),
  last_activity text DEFAULT 'Just joined'
);

-- Create conversations table (matches your app structure)
CREATE TABLE IF NOT EXISTS conversations (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  student_id integer REFERENCES students(id) ON DELETE CASCADE,
  super_coach_id integer REFERENCES super_coaches(id) ON DELETE CASCADE,
  course_id integer REFERENCES courses(id) ON DELETE CASCADE,
  course_version integer DEFAULT 1,
  messages jsonb DEFAULT '[]',
  started_at timestamptz DEFAULT now(),
  last_message_at timestamptz DEFAULT now()
);

-- Keep the existing normalized tables for compatibility with your database schema
-- These tables exist in your actual database but aren't used by the React app

-- Create coaches table (from your existing schema)
CREATE TABLE IF NOT EXISTS coaches (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL,
  email text NOT NULL UNIQUE,
  phone text
);

-- Create course_versions table (from your existing schema)
CREATE TABLE IF NOT EXISTS course_versions (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  course_id integer,
  version_number integer NOT NULL,
  updated_at timestamptz DEFAULT now(),
  is_active boolean DEFAULT true
);

-- Create modules table (from your existing schema)
CREATE TABLE IF NOT EXISTS modules (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  course_id integer,
  title text
);

-- Create tasks table (from your existing schema)
CREATE TABLE IF NOT EXISTS tasks (
  id bigint PRIMARY KEY,
  course_id integer NOT NULL,
  title text NOT NULL,
  deadline date NOT NULL,
  module_id integer NOT NULL,
  timetocomplete bigint
);

-- Create enrollments table (from your existing schema)
CREATE TABLE IF NOT EXISTS enrollments (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  student_id integer,
  course_id integer,
  enrolled_at timestamp DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(student_id, course_id)
);

-- Create task_assignments table (from your existing schema)
CREATE TABLE IF NOT EXISTS task_assignments (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  student_id integer,
  task_id integer,
  status task_status DEFAULT 'pending',
  updated_at timestamptz,
  due_date date NOT NULL,
  UNIQUE(student_id, task_id)
);

-- Create promises table (from your existing schema)
CREATE TABLE IF NOT EXISTS promises (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  student_id integer,
  task_id integer,
  promise_datetime timestamp,
  due_date date,
  checked boolean DEFAULT false,
  created_at timestamp DEFAULT now()
);

-- Enable Row Level Security on all tables
ALTER TABLE super_coaches ENABLE ROW LEVEL SECURITY;
ALTER TABLE courses ENABLE ROW LEVEL SECURITY;
ALTER TABLE students ENABLE ROW LEVEL SECURITY;
ALTER TABLE conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE coaches ENABLE ROW LEVEL SECURITY;
ALTER TABLE course_versions ENABLE ROW LEVEL SECURITY;
ALTER TABLE modules ENABLE ROW LEVEL SECURITY;
ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE enrollments ENABLE ROW LEVEL SECURITY;
ALTER TABLE task_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE promises ENABLE ROW LEVEL SECURITY;

-- Create policies for authenticated users
CREATE POLICY "Allow all operations for authenticated users" ON super_coaches FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow all operations for authenticated users" ON courses FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow all operations for authenticated users" ON students FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow all operations for authenticated users" ON conversations FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow all operations for authenticated users" ON coaches FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow all operations for authenticated users" ON course_versions FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow all operations for authenticated users" ON modules FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow all operations for authenticated users" ON tasks FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow all operations for authenticated users" ON enrollments FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow all operations for authenticated users" ON task_assignments FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow all operations for authenticated users" ON promises FOR ALL TO authenticated USING (true);

-- Insert Super Coaches (for the React app)
INSERT INTO super_coaches (name, personality_type, description, avatar, courses_assigned, created_at, is_active) VALUES
('Coach Maya', 'friendly', 'A warm and encouraging coach who specializes in digital marketing. Maya helps students overcome challenges with patience and positivity.', '', '[]', '2024-01-10T08:00:00Z', true),
('Coach Alexander', 'professional', 'A structured and results-oriented coach focused on leadership development. Alexander provides clear guidance and actionable feedback.', '', '[]', '2024-01-15T10:00:00Z', true),
('Coach Zara', 'motivational', 'An energetic and inspiring coach who helps students push through barriers and achieve their goals with enthusiasm.', '', '[]', '2024-02-01T12:00:00Z', true),
('Coach Sam', 'supportive', 'A patient and understanding coach who provides emotional support and helps students build confidence in their learning journey.', '', '[]', '2024-02-10T14:30:00Z', false);

-- Insert Courses (for the React app with JSON modules)
INSERT INTO courses (title, description, status, version, modules, created_at, updated_at, enrolled_students, completion_rate, super_coach_id, base_id, is_current_version) VALUES
-- Digital Marketing v1 (archived)
('Digital Marketing Mastery', 'Comprehensive course covering all aspects of digital marketing from social media to SEO and paid advertising.', 'archived', 1, '[
  {
    "id": 1,
    "title": "Introduction to Digital Marketing",
    "description": "Learn the fundamentals of digital marketing",
    "order": 1,
    "tasks": [
      {
        "id": 1,
        "title": "What is Digital Marketing?",
        "description": "Overview of digital marketing concepts",
        "type": "video",
        "order": 1,
        "estimatedTime": 30
      },
      {
        "id": 2,
        "title": "Digital Marketing Channels",
        "description": "Understanding different marketing channels",
        "type": "reading",
        "order": 2,
        "estimatedTime": 45
      },
      {
        "id": 3,
        "title": "Quiz: Marketing Basics",
        "description": "Test your understanding of basic concepts",
        "type": "quiz",
        "order": 3,
        "estimatedTime": 15
      }
    ]
  }
]', '2024-01-01T10:00:00Z', '2024-01-15T10:00:00Z', 15, 85, 1, 1, false),

-- Digital Marketing v2 (current live version)
('Digital Marketing Mastery', 'Comprehensive course covering all aspects of digital marketing from social media to SEO and paid advertising.', 'live', 2, '[
  {
    "id": 1,
    "title": "Introduction to Digital Marketing",
    "description": "Learn the fundamentals of digital marketing",
    "order": 1,
    "tasks": [
      {
        "id": 1,
        "title": "What is Digital Marketing?",
        "description": "Overview of digital marketing concepts",
        "type": "video",
        "order": 1,
        "estimatedTime": 30
      },
      {
        "id": 2,
        "title": "Digital Marketing Channels",
        "description": "Understanding different marketing channels",
        "type": "reading",
        "order": 2,
        "estimatedTime": 45
      },
      {
        "id": 3,
        "title": "Quiz: Marketing Basics",
        "description": "Test your understanding of basic concepts",
        "type": "quiz",
        "order": 3,
        "estimatedTime": 15
      }
    ]
  },
  {
    "id": 2,
    "title": "Social Media Marketing",
    "description": "Master social media platforms for marketing",
    "order": 2,
    "tasks": [
      {
        "id": 4,
        "title": "Facebook Marketing Strategy",
        "description": "Learn to create effective Facebook campaigns",
        "type": "video",
        "order": 1,
        "estimatedTime": 60
      },
      {
        "id": 5,
        "title": "Instagram for Business",
        "description": "Leverage Instagram for brand growth",
        "type": "video",
        "order": 2,
        "estimatedTime": 45
      },
      {
        "id": 6,
        "title": "Create a Social Media Plan",
        "description": "Develop your own social media strategy",
        "type": "assignment",
        "order": 3,
        "estimatedTime": 120
      }
    ]
  }
]', '2024-01-15T10:00:00Z', '2024-02-01T14:30:00Z', 45, 68, 1, 1, true),

-- Leadership Excellence v1 (current live version)
('Leadership Excellence', 'Develop essential leadership skills and learn to inspire and manage teams effectively.', 'live', 1, '[
  {
    "id": 3,
    "title": "Leadership Fundamentals",
    "description": "Core principles of effective leadership",
    "order": 1,
    "tasks": [
      {
        "id": 7,
        "title": "What Makes a Great Leader?",
        "description": "Explore leadership qualities and traits",
        "type": "video",
        "order": 1,
        "estimatedTime": 40
      },
      {
        "id": 8,
        "title": "Leadership Styles",
        "description": "Understanding different leadership approaches",
        "type": "reading",
        "order": 2,
        "estimatedTime": 30
      }
    ]
  },
  {
    "id": 4,
    "title": "Team Management",
    "description": "Building and managing high-performing teams",
    "order": 2,
    "tasks": [
      {
        "id": 9,
        "title": "Team Building Strategies",
        "description": "Learn effective team building techniques",
        "type": "video",
        "order": 1,
        "estimatedTime": 50
      },
      {
        "id": 10,
        "title": "Conflict Resolution",
        "description": "Handle team conflicts professionally",
        "type": "assignment",
        "order": 2,
        "estimatedTime": 90
      }
    ]
  }
]', '2024-02-01T09:00:00Z', '2024-02-15T16:45:00Z', 32, 85, 2, 3, true),

-- Digital Marketing v3 (draft)
('Digital Marketing Mastery', 'Comprehensive course covering all aspects of digital marketing from social media to SEO and paid advertising.', 'draft', 3, '[
  {
    "id": 1,
    "title": "Introduction to Digital Marketing",
    "description": "Learn the fundamentals of digital marketing",
    "order": 1,
    "tasks": [
      {
        "id": 1,
        "title": "What is Digital Marketing?",
        "description": "Overview of digital marketing concepts",
        "type": "video",
        "order": 1,
        "estimatedTime": 30
      },
      {
        "id": 2,
        "title": "Digital Marketing Channels",
        "description": "Understanding different marketing channels",
        "type": "reading",
        "order": 2,
        "estimatedTime": 45
      },
      {
        "id": 3,
        "title": "Quiz: Marketing Basics",
        "description": "Test your understanding of basic concepts",
        "type": "quiz",
        "order": 3,
        "estimatedTime": 15
      }
    ]
  },
  {
    "id": 2,
    "title": "Social Media Marketing",
    "description": "Master social media platforms for marketing",
    "order": 2,
    "tasks": [
      {
        "id": 4,
        "title": "Facebook Marketing Strategy",
        "description": "Learn to create effective Facebook campaigns",
        "type": "video",
        "order": 1,
        "estimatedTime": 60
      },
      {
        "id": 5,
        "title": "Instagram for Business",
        "description": "Leverage Instagram for brand growth",
        "type": "video",
        "order": 2,
        "estimatedTime": 45
      },
      {
        "id": 6,
        "title": "Create a Social Media Plan",
        "description": "Develop your own social media strategy",
        "type": "assignment",
        "order": 3,
        "estimatedTime": 120
      }
    ]
  },
  {
    "id": 11,
    "title": "Advanced Analytics",
    "description": "Deep dive into marketing analytics and data interpretation",
    "order": 3,
    "tasks": [
      {
        "id": 11,
        "title": "Google Analytics Setup",
        "description": "Learn to set up and configure Google Analytics",
        "type": "video",
        "order": 1,
        "estimatedTime": 45
      }
    ]
  }
]', '2024-02-20T11:00:00Z', '2024-02-25T10:15:00Z', 0, 0, null, 1, false);

-- Update super coaches with course assignments
UPDATE super_coaches SET courses_assigned = '[1, 2, 4]' WHERE id = 1; -- Maya assigned to Digital Marketing versions
UPDATE super_coaches SET courses_assigned = '[3]' WHERE id = 2; -- Alexander assigned to Leadership

-- Insert Students (for the React app with JSON fields)
INSERT INTO students (name, email, avatar, status, enrolled_courses, progress, joined_at, last_activity) VALUES
('Sarah Johnson', 'sarah.johnson@email.com', null, 'in-progress', '[
  {
    "courseId": 2,
    "courseVersion": 2,
    "enrolledAt": "2024-02-01T10:00:00Z",
    "baseId": 1
  }
]', '[
  {
    "courseId": 2,
    "courseVersion": 2,
    "moduleId": 1,
    "taskId": 1,
    "status": "completed",
    "completedAt": "2024-02-01T10:00:00Z",
    "timeSpent": 35
  },
  {
    "courseId": 2,
    "courseVersion": 2,
    "moduleId": 1,
    "taskId": 2,
    "status": "completed",
    "completedAt": "2024-02-01T11:00:00Z",
    "timeSpent": 50
  },
  {
    "courseId": 2,
    "courseVersion": 2,
    "moduleId": 1,
    "taskId": 3,
    "status": "completed",
    "completedAt": "2024-02-01T12:00:00Z",
    "timeSpent": 20
  },
  {
    "courseId": 2,
    "courseVersion": 2,
    "moduleId": 2,
    "taskId": 4,
    "status": "in-progress",
    "timeSpent": 30
  }
]', '2024-01-20T08:00:00Z', '2 hours ago'),

('Mike Chen', 'mike.chen@email.com', null, 'stuck', '[
  {
    "courseId": 1,
    "courseVersion": 1,
    "enrolledAt": "2024-01-25T10:30:00Z",
    "baseId": 1
  }
]', '[
  {
    "courseId": 1,
    "courseVersion": 1,
    "moduleId": 1,
    "taskId": 1,
    "status": "completed",
    "completedAt": "2024-01-28T14:00:00Z",
    "timeSpent": 40
  },
  {
    "courseId": 1,
    "courseVersion": 1,
    "moduleId": 1,
    "taskId": 2,
    "status": "in-progress",
    "timeSpent": 25
  }
]', '2024-01-25T10:30:00Z', '3 days ago'),

('Emma Rodriguez', 'emma.rodriguez@email.com', null, 'in-progress', '[
  {
    "courseId": 3,
    "courseVersion": 1,
    "enrolledAt": "2024-02-05T14:15:00Z",
    "baseId": 3
  }
]', '[
  {
    "courseId": 3,
    "courseVersion": 1,
    "moduleId": 3,
    "taskId": 7,
    "status": "completed",
    "completedAt": "2024-02-10T09:00:00Z",
    "timeSpent": 45
  },
  {
    "courseId": 3,
    "courseVersion": 1,
    "moduleId": 3,
    "taskId": 8,
    "status": "completed",
    "completedAt": "2024-02-10T10:00:00Z",
    "timeSpent": 35
  },
  {
    "courseId": 3,
    "courseVersion": 1,
    "moduleId": 4,
    "taskId": 9,
    "status": "completed",
    "completedAt": "2024-02-12T11:00:00Z",
    "timeSpent": 55
  },
  {
    "courseId": 3,
    "courseVersion": 1,
    "moduleId": 4,
    "taskId": 10,
    "status": "in-progress",
    "timeSpent": 60
  }
]', '2024-02-05T14:15:00Z', '1 hour ago'),

('David Kim', 'david.kim@email.com', null, 'new', '[
  {
    "courseId": 2,
    "courseVersion": 2,
    "enrolledAt": "2024-02-28T16:45:00Z",
    "baseId": 1
  },
  {
    "courseId": 3,
    "courseVersion": 1,
    "enrolledAt": "2024-02-28T16:45:00Z",
    "baseId": 3
  }
]', '[]', '2024-02-28T16:45:00Z', '5 minutes ago'),

('Lisa Wang', 'lisa.wang@email.com', null, 'completed', '[
  {
    "courseId": 3,
    "courseVersion": 1,
    "enrolledAt": "2024-01-10T12:00:00Z",
    "baseId": 3
  }
]', '[
  {
    "courseId": 3,
    "courseVersion": 1,
    "moduleId": 3,
    "taskId": 7,
    "status": "completed",
    "completedAt": "2024-01-15T09:00:00Z",
    "timeSpent": 45
  },
  {
    "courseId": 3,
    "courseVersion": 1,
    "moduleId": 3,
    "taskId": 8,
    "status": "completed",
    "completedAt": "2024-01-15T10:00:00Z",
    "timeSpent": 35
  },
  {
    "courseId": 3,
    "courseVersion": 1,
    "moduleId": 4,
    "taskId": 9,
    "status": "completed",
    "completedAt": "2024-01-18T11:00:00Z",
    "timeSpent": 55
  },
  {
    "courseId": 3,
    "courseVersion": 1,
    "moduleId": 4,
    "taskId": 10,
    "status": "completed",
    "completedAt": "2024-01-20T14:00:00Z",
    "timeSpent": 95
  }
]', '2024-01-10T12:00:00Z', '1 week ago'),

('Alex Thompson', 'alex.thompson@email.com', null, 'stuck', '[
  {
    "courseId": 1,
    "courseVersion": 1,
    "enrolledAt": "2024-02-10T09:30:00Z",
    "baseId": 1
  }
]', '[
  {
    "courseId": 1,
    "courseVersion": 1,
    "moduleId": 1,
    "taskId": 1,
    "status": "completed",
    "completedAt": "2024-02-15T10:00:00Z",
    "timeSpent": 35
  },
  {
    "courseId": 1,
    "courseVersion": 1,
    "moduleId": 1,
    "taskId": 2,
    "status": "in-progress",
    "timeSpent": 15
  }
]', '2024-02-10T09:30:00Z', '4 days ago');

-- Insert Conversations (for the React app)
INSERT INTO conversations (student_id, super_coach_id, course_id, course_version, messages, started_at, last_message_at) VALUES
(1, 1, 2, 2, '[
  {
    "id": 1,
    "senderId": 1,
    "senderType": "student",
    "content": "Hi Coach Maya! I am having trouble understanding the Facebook advertising module. Could you help me?",
    "timestamp": "2024-02-25T10:00:00Z",
    "type": "text"
  },
  {
    "id": 2,
    "senderId": 1,
    "senderType": "supercoach",
    "content": "Hi Sarah! I would be happy to help you with Facebook advertising. What specific part are you finding challenging?",
    "timestamp": "2024-02-25T10:15:00Z",
    "type": "text"
  }
]', '2024-02-25T10:00:00Z', '2024-02-25T11:00:00Z'),

(3, 2, 3, 1, '[
  {
    "id": 6,
    "senderId": 3,
    "senderType": "student",
    "content": "Coach Alexander, I have completed the team building module and I am really excited to apply these concepts!",
    "timestamp": "2024-02-24T14:00:00Z",
    "type": "text"
  },
  {
    "id": 7,
    "senderId": 2,
    "senderType": "supercoach",
    "content": "Excellent work, Emma! Your enthusiasm is wonderful to see. How do you plan to implement the strategies?",
    "timestamp": "2024-02-24T14:30:00Z",
    "type": "text"
  }
]', '2024-02-24T14:00:00Z', '2024-02-24T15:15:00Z'),

(2, 1, 1, 1, '[
  {
    "id": 10,
    "senderId": 1,
    "senderType": "supercoach",
    "content": "Hi Mike! I noticed you have not been active in the course for a few days. Is everything okay?",
    "timestamp": "2024-02-23T09:00:00Z",
    "type": "text"
  },
  {
    "id": 11,
    "senderId": 2,
    "senderType": "student",
    "content": "Hi Coach Maya, sorry for the delay. I have been really busy at work.",
    "timestamp": "2024-02-26T18:30:00Z",
    "type": "text"
  }
]', '2024-02-23T09:00:00Z', '2024-02-26T19:00:00Z');

-- Insert sample data for the normalized tables (for compatibility)
INSERT INTO coaches (name, email, phone) VALUES
('Coach Maya', 'maya@supercoach.ai', '+1-555-0101'),
('Coach Alexander', 'alexander@supercoach.ai', '+1-555-0102'),
('Coach Zara', 'zara@supercoach.ai', '+1-555-0103'),
('Coach Sam', 'sam@supercoach.ai', '+1-555-0104');